spring.application.name=task-tracker

spring.datasource.url=jdbc:h2:mem:tasktracker;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=false

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=ru.silex.tasktracker.persistence.model
mybatis.configuration.map-underscore-to-camel-case=true
